@startuml
start
skinparam titleBorderRoundCorner 14
skinparam titleBorderColor red
skinparam titleBackgroundColor Moccasin
title **Алгоритм выполнения контролей по данным консолидации**
:Получение uuid задачи сбора отчетности по параметрам:
*год
*период;
note left
http-запрос, 
с указанными 
параметрами
(также происходит
получение и 
других данных
из консолидации)
end note
:Получение списка uuid отчетности по параметрам:
*тип отчетности
*uuid задачи сбора отчетности
*роль субъекта отчетности
*статус отчетности;
:Получение uuid отчета по параметрам:
*инн
*кпп
*бюджет;
:Получение отчета по этому uuid;
:Преобразование отчета в формат планирования;
note left
Используются 
xpath-выражения,
указанные в 
настройках контроля
end note
:Фильтрация данных отчета;
note left
Используется фильтр,
указанный в 
настройках контроля
end note
:Фильтрация данных планирования;
:Сравнение сумм данных планирования и консолидации;
:Вывод результата;
note left
html-таблица
со списком 
классификации
и сумм
end note
stop
@enduml